version: '3.9'
services:
    sqlserver:
        build:
            dockerfile: ./SiteMercado.Domain.Infra/Dockerfile
            context: ./
        image: sqlserver
        user: root
        ports:
            - "11433:1433"
        expose: 
            - 11433
        container_name: sqlservice
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "sqlserver@123"
        networks: 
            - crudprodutosnet

    backend:
        build:
            dockerfile: ./SiteMercado.Domain.Api/Dockerfile
            context: ./
        image: backend
        ports:
            - "5000:80"
        container_name: backend
        depends_on:
            - "sqlserver"
        networks: 
            - crudprodutosnet

    frontend:
        build:
            context: ./
            dockerfile: ./SiteMercado.App/Dockerfile
        ports:
            - "8081:8080"
        container_name: vue-ui
        image: frontend
        depends_on:
            - "backend"
                   

networks:
  crudprodutosnet:
    driver: bridge
    

